# Generated by Django 5.1.5 on 2025-02-09 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle_detection", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videoupload",
            name="user",
        ),
    ]
